USE ctep;

DELETE FROM PROFESSOR_TURMA;

DELETE FROM OBSERVACAO_ALUNO;
DELETE FROM OBSERVACAO_TURMA;
DELETE FROM NOTA_ALUNO;DELETE FROM DISCIPLINA;
DELETE FROM RECIBO_PROFESSOR;
DELETE FROM ESTAGIO_ALUNO;
DELETE FROM HOSPITAL;
DELETE FROM MODALIDADE_ESTAGIO;

DELETE FROM PROFESSOR;
DELETE FROM ALUNO;
DELETE FROM TURMA;
DELETE FROM CURSO;
DELETE FROM USUARIO;