use ctep;

DROP TABLE IF EXISTS PROFESSOR_TURMA;

DROP TABLE IF EXISTS OBSERVACAO_ALUNO;
DROP TABLE IF EXISTS OBSERVACAO_TURMA;
DROP TABLE IF EXISTS DISCIPLINA;
DROP TABLE IF EXISTS RECIBO_PROFESSOR;
DROP TABLE IF EXISTS ESTAGIO_ALUNO;
DROP TABLE IF EXISTS HOSPITAL;
DROP TABLE IF EXISTS MODALIDADE_ESTAGIO;

DROP TABLE IF EXISTS PROFESSOR;
DROP TABLE IF EXISTS ALUNO;
DROP TABLE IF EXISTS TURMA;
DROP TABLE IF EXISTS CURSO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS NOTA_ALUNO;

