USE ctep;

DELETE FROM ALUNO;
DELETE FROM USUARIO;
DELETE FROM PROFESSOR;
DELETE FROM RECIBO_PROFESSOR;
DELETE FROM TURMA;
DELETE FROM OBSERVACAO_ALUNO;
DELETE FROM OBSERVACAO_TURMA;
DELETE FROM DISCIPLINA;
DELETE FROM CURSO;