USE ctep;

DROP TABLE IF EXISTS PROFESSOR_TURMA;

CREATE TABLE PROFESSOR_TURMA (
  ID           INT(3) AUTO_INCREMENT NOT NULL,
  PROFESSOR_ID INT(5),
  TURMA_CODIGO VARCHAR(8),

  CONSTRAINT PK_PROFESSOR_TURMA_ID PRIMARY KEY (ID),
  CONSTRAINT FK_PROFESSOR_TURMA_ID FOREIGN KEY (PROFESSOR_ID) REFERENCES PROFESSOR (ID),
  CONSTRAINT FK_TURMA_PROFESSOR_CODIGO FOREIGN KEY (TURMA_CODIGO) REFERENCES TURMA (CODIGO)
);
